spring.application.name=gym-crm
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=gym-crm

security.jwt.secret-base64=${JWT_SECRET_BASE64:MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=}
security.jwt.expiration-minutes=30

security.login.max-failed-attempts=3
security.login.block-duration-minutes=5

security.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}



resilience4j.retry.instances.trainerWorkload.max-attempts=3
resilience4j.retry.instances.trainerWorkload.wait-duration=500ms

resilience4j.circuitbreaker.instances.trainerWorkload.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.trainerWorkload.sliding-window-size=5
resilience4j.circuitbreaker.instances.trainerWorkload.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.trainerWorkload.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.trainerWorkload.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.trainerWorkload.permitted-number-of-calls-in-half-open-state=2

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
trainer-workload-service.base-url=http://trainer-workload-service
